# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/intersect/JunkaiSuo524370910105-p2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/intersect/JunkaiSuo524370910105-p2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/intersect/JunkaiSuo524370910105-p2/CMakeFiles /home/intersect/JunkaiSuo524370910105-p2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/intersect/JunkaiSuo524370910105-p2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/intersect/JunkaiSuo524370910105-p2/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named onecard

# Build rule for target.
onecard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 onecard
.PHONY : onecard

# fast build rule for target.
onecard/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/onecard.dir/build.make CMakeFiles/onecard.dir/build
.PHONY : onecard/fast

#=============================================================================
# Target rules for targets named ubsan

# Build rule for target.
ubsan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ubsan
.PHONY : ubsan

# fast build rule for target.
ubsan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ubsan.dir/build.make CMakeFiles/ubsan.dir/build
.PHONY : ubsan/fast

#=============================================================================
# Target rules for targets named asan

# Build rule for target.
asan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asan
.PHONY : asan

# fast build rule for target.
asan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asan.dir/build.make CMakeFiles/asan.dir/build
.PHONY : asan/fast

#=============================================================================
# Target rules for targets named msan

# Build rule for target.
msan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 msan
.PHONY : msan

# fast build rule for target.
msan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msan.dir/build.make CMakeFiles/msan.dir/build
.PHONY : msan/fast

src/baseFunc.o: src/baseFunc.c.o
.PHONY : src/baseFunc.o

# target to build an object file
src/baseFunc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/onecard.dir/build.make CMakeFiles/onecard.dir/src/baseFunc.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ubsan.dir/build.make CMakeFiles/ubsan.dir/src/baseFunc.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asan.dir/build.make CMakeFiles/asan.dir/src/baseFunc.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msan.dir/build.make CMakeFiles/msan.dir/src/baseFunc.c.o
.PHONY : src/baseFunc.c.o

src/baseFunc.i: src/baseFunc.c.i
.PHONY : src/baseFunc.i

# target to preprocess a source file
src/baseFunc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/onecard.dir/build.make CMakeFiles/onecard.dir/src/baseFunc.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ubsan.dir/build.make CMakeFiles/ubsan.dir/src/baseFunc.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asan.dir/build.make CMakeFiles/asan.dir/src/baseFunc.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msan.dir/build.make CMakeFiles/msan.dir/src/baseFunc.c.i
.PHONY : src/baseFunc.c.i

src/baseFunc.s: src/baseFunc.c.s
.PHONY : src/baseFunc.s

# target to generate assembly for a file
src/baseFunc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/onecard.dir/build.make CMakeFiles/onecard.dir/src/baseFunc.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ubsan.dir/build.make CMakeFiles/ubsan.dir/src/baseFunc.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asan.dir/build.make CMakeFiles/asan.dir/src/baseFunc.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msan.dir/build.make CMakeFiles/msan.dir/src/baseFunc.c.s
.PHONY : src/baseFunc.c.s

src/compFunc.o: src/compFunc.c.o
.PHONY : src/compFunc.o

# target to build an object file
src/compFunc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/onecard.dir/build.make CMakeFiles/onecard.dir/src/compFunc.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ubsan.dir/build.make CMakeFiles/ubsan.dir/src/compFunc.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asan.dir/build.make CMakeFiles/asan.dir/src/compFunc.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msan.dir/build.make CMakeFiles/msan.dir/src/compFunc.c.o
.PHONY : src/compFunc.c.o

src/compFunc.i: src/compFunc.c.i
.PHONY : src/compFunc.i

# target to preprocess a source file
src/compFunc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/onecard.dir/build.make CMakeFiles/onecard.dir/src/compFunc.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ubsan.dir/build.make CMakeFiles/ubsan.dir/src/compFunc.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asan.dir/build.make CMakeFiles/asan.dir/src/compFunc.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msan.dir/build.make CMakeFiles/msan.dir/src/compFunc.c.i
.PHONY : src/compFunc.c.i

src/compFunc.s: src/compFunc.c.s
.PHONY : src/compFunc.s

# target to generate assembly for a file
src/compFunc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/onecard.dir/build.make CMakeFiles/onecard.dir/src/compFunc.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ubsan.dir/build.make CMakeFiles/ubsan.dir/src/compFunc.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asan.dir/build.make CMakeFiles/asan.dir/src/compFunc.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msan.dir/build.make CMakeFiles/msan.dir/src/compFunc.c.s
.PHONY : src/compFunc.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/onecard.dir/build.make CMakeFiles/onecard.dir/src/main.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ubsan.dir/build.make CMakeFiles/ubsan.dir/src/main.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asan.dir/build.make CMakeFiles/asan.dir/src/main.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msan.dir/build.make CMakeFiles/msan.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/onecard.dir/build.make CMakeFiles/onecard.dir/src/main.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ubsan.dir/build.make CMakeFiles/ubsan.dir/src/main.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asan.dir/build.make CMakeFiles/asan.dir/src/main.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msan.dir/build.make CMakeFiles/msan.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/onecard.dir/build.make CMakeFiles/onecard.dir/src/main.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ubsan.dir/build.make CMakeFiles/ubsan.dir/src/main.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asan.dir/build.make CMakeFiles/asan.dir/src/main.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msan.dir/build.make CMakeFiles/msan.dir/src/main.c.s
.PHONY : src/main.c.s

src/printing.o: src/printing.c.o
.PHONY : src/printing.o

# target to build an object file
src/printing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/onecard.dir/build.make CMakeFiles/onecard.dir/src/printing.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ubsan.dir/build.make CMakeFiles/ubsan.dir/src/printing.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asan.dir/build.make CMakeFiles/asan.dir/src/printing.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msan.dir/build.make CMakeFiles/msan.dir/src/printing.c.o
.PHONY : src/printing.c.o

src/printing.i: src/printing.c.i
.PHONY : src/printing.i

# target to preprocess a source file
src/printing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/onecard.dir/build.make CMakeFiles/onecard.dir/src/printing.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ubsan.dir/build.make CMakeFiles/ubsan.dir/src/printing.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asan.dir/build.make CMakeFiles/asan.dir/src/printing.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msan.dir/build.make CMakeFiles/msan.dir/src/printing.c.i
.PHONY : src/printing.c.i

src/printing.s: src/printing.c.s
.PHONY : src/printing.s

# target to generate assembly for a file
src/printing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/onecard.dir/build.make CMakeFiles/onecard.dir/src/printing.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ubsan.dir/build.make CMakeFiles/ubsan.dir/src/printing.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asan.dir/build.make CMakeFiles/asan.dir/src/printing.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msan.dir/build.make CMakeFiles/msan.dir/src/printing.c.s
.PHONY : src/printing.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... asan"
	@echo "... msan"
	@echo "... onecard"
	@echo "... ubsan"
	@echo "... src/baseFunc.o"
	@echo "... src/baseFunc.i"
	@echo "... src/baseFunc.s"
	@echo "... src/compFunc.o"
	@echo "... src/compFunc.i"
	@echo "... src/compFunc.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/printing.o"
	@echo "... src/printing.i"
	@echo "... src/printing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/intersect/JunkaiSuo524370910105-p2/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

